##
# Preflight
##

# Tap homebrew
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"


# Brew
brew "ansible"
brew "black"
brew "bpytop"
brew "cask"
brew "docker"
brew "dos2unix"
brew "figlet"
brew "git"
brew "isort"
brew "jq"
brew "pyenv"
brew "python"
brew "pv"
brew "speedtest-cli"
brew "tree"
brew "wget"
brew "wifi-password"
brew "yq"

# Cask
cask "docker"
cask "dotnet"
cask "dropbox"
cask "franz"
cask "google-chrome"
cask "iterm2"
cask "sublime-text"
cask "visual-studio-code"
cask "vlc"
